### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by macor161** [espresso-org/aragon-datastore#111]
Right now, documentation for the Datastore is complete but has the following flaws:
 - Not easy to navigate
 - Private variables and functions are displayed by default
 - Doc has to be generated manualy

We should therefore:
 1. Build a bash script intended to be run after typedoc and that :
    - Replaces `doc/index.html` with `doc/classes/_index_.datastore.html` 
    - Replaces every instance of `../` with `./` inside `doc/index.html` 
    - Adds the following line to the header of `doc/index.html` : `<script>localStorage.setItem('visibility', 'public')</script>` 
 2. Change the `doc` script inside `package.json` so it runs our new bash script afterwards
 3. Change the `build` script inside `package.json` so it runs the `doc` script after the build

**Comment by juslar** [comment]
Done! Pushed directly on `development` :)
