### ISSUE TITLE
Rename package to @espresso-org/...

### ISSUE THREAD

**Issue by macor161** [espresso-org/aragon-datastore#26]
We have a new npm organization: www.npmjs.com/org/espresso-org
For the sake of uniformity, we should standardize our package names around this organization.
Here are some propositions for the Datastore, feel free to add your own:

- @espresso-org/aragon-datastore
- @espresso-org/datastore
- @espresso-org/decentralized-datastore
- something else?

**Comment by juslar** [comment]
@espresso-org/aragon-datastore sounds good to me.

**Comment by juslar** [comment]
No need to change this package's name as it already fits with our chosen naming scheme. We can close this issue.
