### ISSUE TITLE
Add support for groups

### ISSUE THREAD

**Issue by macor161** [espresso-org/aragon-datastore#31]
### Add support for groups

A common use case for file permissions is to have groups of people with same access to specific files/folders. It would be a great addition to the Datastore if we could support something similar.

### Contract interface proposal

- createGroup(string _group, address[] _entities)
- deleteGroup(string _group)
- renameGroup(string _group, string _newGroupName)
- addEntityToGroup(string _group, address _entity)
- removeEntityFromGroup(string _group, address _entity)
- setGroupPermissions(uint _fileId, string _group, bool _read, bool _write)
- removeGroupFromFile(uint _fileId, string _group)

**Comment by macor161** [comment]
Just realized that with `addGroupToFile(uint _fileId, string _group)`, we didn't have any way to set the permissions for that group. 

So I changed it to `setGroupPermissions(uint _fileId, string _group, bool _read, bool _write)`
What do you think?

**Comment by juslar** [comment]
You're right. Great!
