### ISSUE TITLE
Doc simplification

### ISSUE THREAD

**Issue by macor161** [espresso-org/aragon-datastore#73]
Great job for the documentation! 

However it doesn't seem possible to access the main javascript file documentation page from the `doc/index.html` page. And the links don't seem to work. 

Also, is there a way to remove all the information about the "globals" files and private variables? I'm not convinced this information is very useful for users.

**Comment by juslar** [comment]
You're right about the broken links. Had to do with all the useless docs I removed.

The options with `typedoc` are limited so I'm afraid I can't remove all the random informations we don't want with a simple command.. My suggestion is to keep the whole thing for now and manually improve/customize it like we want at the end of the project.

I pushed the complete docs with no broken links on dev. I'll close this issue :)
